apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-runner-controller
  namespace: github-runner
spec:
  interval: 1h
  url: file://./github-runner/gha-runner-scale-set-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-runner-controller
  namespace: github-runner
spec:
  interval: 1h
  chart:
    spec:
      chart: ./github-runner/gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: github-runner-controller
        namespace: github-runner
      valuesFiles:
        - ./github-runner/gha-runner-scale-set-controller/values.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-runner-scale-set
  namespace: github-runner
spec:
  interval: 1h
  url: file://./github-runner/gha-runner-scale-set
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-runner-scale-set
  namespace: github-runner
spec:
  interval: 1h
  dependsOn:
    - name: github-runner-controller
  chart:
    spec:
      chart: ./github-runner/gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: github-runner-scale-set
        namespace: github-runner
      valuesFiles:
        - ./github-runner/gha-runner-scale-set/values-airflow-gke.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
