apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 1h
  url: file://./airflow/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 1h
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  chart:
    spec:
      chart: ./airflow/helm
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: airflow
      valuesFiles:
        - ./airflow/helm/values-gke.yaml
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
