# NFS Persistent Volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${nfs_server}  # Will be substituted by Config Sync
    path: /mnt/disks/airflow-disk/airflow/logs
  mountOptions:
    - rsize=131072
    - wsize=131072
    - nfsvers=4.1
    - noatime
    - nolock
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${nfs_server}  # Will be substituted by Config Sync
    path: /mnt/disks/airflow-disk/airflow/dags
  mountOptions:
    - rsize=131072
    - wsize=131072
    - nfsvers=4.1
    - noatime
    - nolock
  persistentVolumeReclaimPolicy: Retain
---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: airflow-logs
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: airflow-dags
  storageClassName: ""
